export const FETCH_BRANCHDATA_REQUEST = "FETCH_BRANCHDATA_REQUEST";
export const FETCH_BRANCHDATA_SUCCESS = "FETCH_BRANCHDATA_SUCCESS";
export const FETCH_BRANCHDATA_FAILURE = "FETCH_BRANCHDATA_FAILURE";
export const SET_SELECTED_BRANCH = "SET_SELECTED_BRANCH";
