export const telephoneCodes = [
  { value: "AD", label: "Andorra", key: "376" },
  {
    value: "AE",
    label: "United Arab Emirates",
    key: "971",
  },
  { value: "AF", label: "Afghanistan", key: "93" },
  {
    value: "AG",
    label: "Antigua and Barbuda",
    key: "1-268",
  },
  { value: "AI", label: "Anguilla", key: "1-264" },
  { value: "AL", label: "Albania", key: "355" },
  { value: "AM", label: "Armenia", key: "374" },
  { value: "AO", label: "Angola", key: "244" },
  { value: "AQ", label: "Antarctica", key: "672" },
  { value: "AR", label: "Argentina", key: "54" },
  { value: "AS", label: "American Samoa", key: "1-684" },
  { value: "AT", label: "Austria", key: "43" },
  {
    value: "AU",
    label: "Australia",
    key: "61",
    suggested: true,
  },
  { value: "AW", label: "Aruba", key: "297" },
  { value: "AX", label: "Alland Islands", key: "358" },
  { value: "AZ", label: "Azerbaijan", key: "994" },
  {
    value: "BA",
    label: "Bosnia and Herzegovina",
    key: "387",
  },
  { value: "BB", label: "Barbados", key: "1-246" },
  { value: "BD", label: "Bangladesh", key: "880" },
  { value: "BE", label: "Belgium", key: "32" },
  { value: "BF", label: "Burkina Faso", key: "226" },
  { value: "BG", label: "Bulgaria", key: "359" },
  { value: "BH", label: "Bahrain", key: "973" },
  { value: "BI", label: "Burundi", key: "257" },
  { value: "BJ", label: "Benin", key: "229" },
  { value: "BL", label: "Saint Barthelemy", key: "590" },
  { value: "BM", label: "Bermuda", key: "1-441" },
  { value: "BN", label: "Brunei Darussalam", key: "673" },
  { value: "BO", label: "Bolivia", key: "591" },
  { value: "BR", label: "Brazil", key: "55" },
  { value: "BS", label: "Bahamas", key: "1-242" },
  { value: "BT", label: "Bhutan", key: "975" },
  { value: "BV", label: "Bouvet Island", key: "47" },
  { value: "BW", label: "Botswana", key: "267" },
  { value: "BY", label: "Belarus", key: "375" },
  { value: "BZ", label: "Belize", key: "501" },
  {
    value: "CA",
    label: "Canada",
    key: "1",
    suggested: true,
  },
  {
    value: "CC",
    label: "Cocos (Keeling) Islands",
    key: "61",
  },
  {
    value: "CD",
    label: "Congo, Democratic Republic of the",
    key: "243",
  },
  {
    value: "CF",
    label: "Central African Republic",
    key: "236",
  },
  {
    value: "CG",
    label: "Congo, Republic of the",
    key: "242",
  },
  { value: "CH", label: "Switzerland", key: "41" },
  { value: "CI", label: "Cote d'Ivoire", key: "225" },
  { value: "CK", label: "Cook Islands", key: "682" },
  { value: "CL", label: "Chile", key: "56" },
  { value: "CM", label: "Cameroon", key: "237" },
  { value: "CN", label: "China", key: "86" },
  { value: "CO", label: "Colombia", key: "57" },
  { value: "CR", label: "Costa Rica", key: "506" },
  { value: "CU", label: "Cuba", key: "53" },
  { value: "CV", label: "Cape Verde", key: "238" },
  { value: "CW", label: "Curacao", key: "599" },
  { value: "CX", label: "Christmas Island", key: "61" },
  { value: "CY", label: "Cyprus", key: "357" },
  { value: "CZ", label: "Czech Republic", key: "420" },
  {
    value: "DE",
    label: "Germany",
    key: "49",
    suggested: true,
  },
  { value: "DJ", label: "Djibouti", key: "253" },
  { value: "DK", label: "Denmark", key: "45" },
  { value: "DM", label: "Dominica", key: "1-767" },
  {
    value: "DO",
    label: "Dominican Republic",
    key: "1-809",
  },
  { value: "DZ", label: "Algeria", key: "213" },
  { value: "EC", label: "Ecuador", key: "593" },
  { value: "EE", label: "Estonia", key: "372" },
  { value: "EG", label: "Egypt", key: "20" },
  { value: "EH", label: "Western Sahara", key: "212" },
  { value: "ER", label: "Eritrea", key: "291" },
  { value: "ES", label: "Spain", key: "34" },
  { value: "ET", label: "Ethiopia", key: "251" },
  { value: "FI", label: "Finland", key: "358" },
  { value: "FJ", label: "Fiji", key: "679" },
  {
    value: "FK",
    label: "Falkland Islands (Malvinas)",
    key: "500",
  },
  {
    value: "FM",
    label: "Micronesia, Federated States of",
    key: "691",
  },
  { value: "FO", label: "Faroe Islands", key: "298" },
  {
    value: "FR",
    label: "France",
    key: "33",
    suggested: true,
  },
  { value: "GA", label: "Gabon", key: "241" },
  { value: "GB", label: "United Kingdom", key: "44" },
  { value: "GD", label: "Grenada", key: "1-473" },
  { value: "GE", label: "Georgia", key: "995" },
  { value: "GF", label: "French Guiana", key: "594" },
  { value: "GG", label: "Guernsey", key: "44" },
  { value: "GH", label: "Ghana", key: "233" },
  { value: "GI", label: "Gibraltar", key: "350" },
  { value: "GL", label: "Greenland", key: "299" },
  { value: "GM", label: "Gambia", key: "220" },
  { value: "GN", label: "Guinea", key: "224" },
  { value: "GP", label: "Guadeloupe", key: "590" },
  { value: "GQ", label: "Equatorial Guinea", key: "240" },
  { value: "GR", label: "Greece", key: "30" },
  {
    value: "GS",
    label: "South Georgia and the South Sandwich Islands",
    key: "500",
  },
  { value: "GT", label: "Guatemala", key: "502" },
  { value: "GU", label: "Guam", key: "1-671" },
  { value: "GW", label: "Guinea-Bissau", key: "245" },
  { value: "GY", label: "Guyana", key: "592" },
  { value: "HK", label: "Hong Kong", key: "852" },
  {
    value: "HM",
    label: "Heard Island and McDonald Islands",
    key: "672",
  },
  { value: "HN", label: "Honduras", key: "504" },
  { value: "HR", label: "Croatia", key: "385" },
  { value: "HT", label: "Haiti", key: "509" },
  { value: "HU", label: "Hungary", key: "36" },
  { value: "ID", label: "Indonesia", key: "62" },
  { value: "IE", label: "Ireland", key: "353" },
  { value: "IL", label: "Israel", key: "972" },
  { value: "IM", label: "Isle of Man", key: "44" },
  { value: "IN", label: "India", key: "91" },
  {
    value: "IO",
    label: "British Indian Ocean Territory",
    key: "246",
  },
  { value: "IQ", label: "Iraq", key: "964" },
  {
    value: "IR",
    label: "Iran, Islamic Republic of",
    key: "98",
  },
  { value: "IS", label: "Iceland", key: "354" },
  { value: "IT", label: "Italy", key: "39" },
  { value: "JE", label: "Jersey", key: "44" },
  { value: "JM", label: "Jamaica", key: "1-876" },
  { value: "JO", label: "Jordan", key: "962" },
  {
    value: "JP",
    label: "Japan",
    key: "81",
    suggested: true,
  },
  { value: "KE", label: "Kenya", key: "254" },
  { value: "KG", label: "Kyrgyzstan", key: "996" },
  { value: "KH", label: "Cambodia", key: "855" },
  { value: "KI", label: "Kiribati", key: "686" },
  { value: "KM", label: "Comoros", key: "269" },
  {
    value: "KN",
    label: "Saint Kitts and Nevis",
    key: "1-869",
  },
  {
    value: "KP",
    label: "Korea, Democratic People's Republic of",
    key: "850",
  },
  { value: "KR", label: "Korea, Republic of", key: "82" },
  { value: "KW", label: "Kuwait", key: "965" },
  { value: "KY", label: "Cayman Islands", key: "1-345" },
  { value: "KZ", label: "Kazakhstan", key: "7" },
  {
    value: "LA",
    label: "Lao People's Democratic Republic",
    key: "856",
  },
  { value: "LB", label: "Lebanon", key: "961" },
  { value: "LC", label: "Saint Lucia", key: "1-758" },
  { value: "LI", label: "Liechtenstein", key: "423" },
  { value: "LK", label: "Sri Lanka", key: "94" },
  { value: "LR", label: "Liberia", key: "231" },
  { value: "LS", label: "Lesotho", key: "266" },
  { value: "LT", label: "Lithuania", key: "370" },
  { value: "LU", label: "Luxembourg", key: "352" },
  { value: "LV", label: "Latvia", key: "371" },
  { value: "LY", label: "Libya", key: "218" },
  { value: "MA", label: "Morocco", key: "212" },
  { value: "MC", label: "Monaco", key: "377" },
  {
    value: "MD",
    label: "Moldova, Republic of",
    key: "373",
  },
  { value: "ME", label: "Montenegro", key: "382" },
  {
    value: "MF",
    label: "Saint Martin (French part)",
    key: "590",
  },
  { value: "MG", label: "Madagascar", key: "261" },
  { value: "MH", label: "Marshall Islands", key: "692" },
  {
    value: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    key: "389",
  },
  { value: "ML", label: "Mali", key: "223" },
  { value: "MM", label: "Myanmar", key: "95" },
  { value: "MN", label: "Mongolia", key: "976" },
  { value: "MO", label: "Macao", key: "853" },
  {
    value: "MP",
    label: "Northern Mariana Islands",
    key: "1-670",
  },
  { value: "MQ", label: "Martinique", key: "596" },
  { value: "MR", label: "Mauritania", key: "222" },
  { value: "MS", label: "Montserrat", key: "1-664" },
  { value: "MT", label: "Malta", key: "356" },
  { value: "MU", label: "Mauritius", key: "230" },
  { value: "MV", label: "Maldives", key: "960" },
  { value: "MW", label: "Malawi", key: "265" },
  { value: "MX", label: "Mexico", key: "52" },
  { value: "MY", label: "Malaysia", key: "60" },
  { value: "MZ", label: "Mozambique", key: "258" },
  { value: "NA", label: "Namibia", key: "264" },
  { value: "NC", label: "New Caledonia", key: "687" },
  { value: "NE", label: "Niger", key: "227" },
  { value: "NF", label: "Norfolk Island", key: "672" },
  { value: "NG", label: "Nigeria", key: "234" },
  { value: "NI", label: "Nicaragua", key: "505" },
  { value: "NL", label: "Netherlands", key: "31" },
  { value: "NO", label: "Norway", key: "47" },
  { value: "NP", label: "Nepal", key: "977" },
  { value: "NR", label: "Nauru", key: "674" },
  { value: "NU", label: "Niue", key: "683" },
  { value: "NZ", label: "New Zealand", key: "64" },
  { value: "OM", label: "Oman", key: "968" },
  { value: "PA", label: "Panama", key: "507" },
  { value: "PE", label: "Peru", key: "51" },
  { value: "PF", label: "French Polynesia", key: "689" },
  { value: "PG", label: "Papua New Guinea", key: "675" },
  { value: "PH", label: "Philippines", key: "63" },
  { value: "PK", label: "Pakistan", key: "92" },
  { value: "PL", label: "Poland", key: "48" },
  {
    value: "PM",
    label: "Saint Pierre and Miquelon",
    key: "508",
  },
  { value: "PN", label: "Pitcairn", key: "870" },
  { value: "PR", label: "Puerto Rico", key: "1" },
  {
    value: "PS",
    label: "Palestine, State of",
    key: "970",
  },
  { value: "PT", label: "Portugal", key: "351" },
  { value: "PW", label: "Palau", key: "680" },
  { value: "PY", label: "Paraguay", key: "595" },
  { value: "QA", label: "Qatar", key: "974" },
  { value: "RE", label: "Reunion", key: "262" },
  { value: "RO", label: "Romania", key: "40" },
  { value: "RS", label: "Serbia", key: "381" },
  { value: "RU", label: "Russian Federation", key: "7" },
  { value: "RW", label: "Rwanda", key: "250" },
  { value: "SA", label: "Saudi Arabia", key: "966" },
  { value: "SB", label: "Solomon Islands", key: "677" },
  { value: "SC", label: "Seychelles", key: "248" },
  { value: "SD", label: "Sudan", key: "249" },
  { value: "SE", label: "Sweden", key: "46" },
  { value: "SG", label: "Singapore", key: "65" },
  { value: "SH", label: "Saint Helena", key: "290" },
  { value: "SI", label: "Slovenia", key: "386" },
  {
    value: "SJ",
    label: "Svalbard and Jan Mayen",
    key: "47",
  },
  { value: "SK", label: "Slovakia", key: "421" },
  { value: "SL", label: "Sierra Leone", key: "232" },
  { value: "SM", label: "San Marino", key: "378" },
  { value: "SN", label: "Senegal", key: "221" },
  { value: "SO", label: "Somalia", key: "252" },
  { value: "SR", label: "Suriname", key: "597" },
  { value: "SS", label: "South Sudan", key: "211" },
  {
    value: "ST",
    label: "Sao Tome and Principe",
    key: "239",
  },
  { value: "SV", label: "El Salvador", key: "503" },
  {
    value: "SX",
    label: "Sint Maarten (Dutch part)",
    key: "1-721",
  },
  {
    value: "SY",
    label: "Syrian Arab Republic",
    key: "963",
  },
  { value: "SZ", label: "Swaziland", key: "268" },
  {
    value: "TC",
    label: "Turks and Caicos Islands",
    key: "1-649",
  },
  { value: "TD", label: "Chad", key: "235" },
  {
    value: "TF",
    label: "French Southern Territories",
    key: "262",
  },
  { value: "TG", label: "Togo", key: "228" },
  { value: "TH", label: "Thailand", key: "66" },
  { value: "TJ", label: "Tajikistan", key: "992" },
  { value: "TK", label: "Tokelau", key: "690" },
  { value: "TL", label: "Timor-Leste", key: "670" },
  { value: "TM", label: "Turkmenistan", key: "993" },
  { value: "TN", label: "Tunisia", key: "216" },
  { value: "TO", label: "Tonga", key: "676" },
  { value: "TR", label: "Turkey", key: "90" },
  {
    value: "TT",
    label: "Trinidad and Tobago",
    key: "1-868",
  },
  { value: "TV", label: "Tuvalu", key: "688" },
  {
    value: "TW",
    label: "Taiwan, Province of China",
    key: "886",
  },
  {
    value: "TZ",
    label: "United Republic of Tanzania",
    key: "255",
  },
  { value: "UA", label: "Ukraine", key: "380" },
  { value: "UG", label: "Uganda", key: "256" },
  {
    value: "US",
    label: "United States",
    key: "1",
    suggested: true,
  },
  { value: "UY", label: "Uruguay", key: "598" },
  { value: "UZ", label: "Uzbekistan", key: "998" },
  {
    value: "VA",
    label: "Holy See (Vatican City State)",
    key: "379",
  },
  {
    value: "VC",
    label: "Saint Vincent and the Grenadines",
    key: "1-784",
  },
  { value: "VE", label: "Venezuela", key: "58" },
  {
    value: "VG",
    label: "British Virgin Islands",
    key: "1-284",
  },
  {
    value: "VI",
    label: "US Virgin Islands",
    key: "1-340",
  },
  { value: "VN", label: "Vietnam", key: "84" },
  { value: "VU", label: "Vanuatu", key: "678" },
  { value: "WF", label: "Wallis and Futuna", key: "681" },
  { value: "WS", label: "Samoa", key: "685" },
  { value: "XK", label: "Kosovo", key: "383" },
  { value: "YE", label: "Yemen", key: "967" },
  { value: "YT", label: "Mayotte", key: "262" },
  { value: "ZA", label: "South Africa", key: "27" },
  { value: "ZM", label: "Zambia", key: "260" },
  { value: "ZW", label: "Zimbabwe", key: "263" },
];
